[build]
  command = "CI=false npm ci --legacy-peer-deps && npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_OPTIONS = "--openssl-legacy-provider"
  NODE_ENV = "production"

[dev]
  command = "npm start"
  port = 3000
